server:
  port: 8090
  http2:
    enabled: true
  ssl:
    key-store-type: PKCS12
    key-store: classpath:keystore.p12
    key-store-password: password
    key-password: password
    enabled: false
spring:
  cloud:
    gateway:
      httpclient:
        ssl:
          use-insecure-trust-manager: true

      routes:
        - id: grpc-path
          uri: lb:http://grpc-server
          metadata:
            h2c: true
          predicates:
            - Header=custom_client_header_key, grpc-path
          filters:
            - AddResponseHeader=X-Request-header, header-value